# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Build PDF

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          # cache: 'pip'
      - name: Clone Docs
        run: |
          # GIT_LFS_SKIP_SMUDGE=1 git clone -b dev --depth 1 https://${{ secrets.SMDDOCUMENTATIONTOKEN }}@github.com/Bertz-TII/SMDExplorer-Documentation.git
          git clone -b dev --depth 1 https://${{ secrets.SMDDOCUMENTATIONTOKEN }}@github.com/Bertz-TII/SMDExplorer-Documentation.git

          python -m pip install --upgrade pip
          cd SMDExplorer-Documentation
          ls
          pip install -r requirements.txt
       
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          
      - name: build_tex
        run: |
          sudo apt-get install texlive-extra-utils
          
          npm install -g @mermaid-js/mermaid-cli
          cd SMDExplorer-Documentation/docs/source
          
          sphinx-build -E -b latex -D language=en -D latex_engine=lualatex . ../build/tex_en
          sphinx-build -E -b latex -D language=ja -D latex_engine=uplatex . ../build/tex_ja

      - uses: xu-cheng/texlive-action@v3
        with:
            run: |
                cd SMDExplorer-Documentation/docs/build/tex_en
                export XINDYOPTS="-L english -C utf8  -M sphinx.xdy"
                latexmk -pdf -dvi- -ps-
                mv smdexplorer.pdf smdexplorer_en.pdf
                cd ../tex_ja
                export XINDYOPTS=""
                latexmk -r latexmkjarc -pdfdvi -dvi- -ps-
                mv smdexplorer.pdf smdexplorer_ja.pdf

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: tex
          path: |
            ./SMDExplorer-Documentation/docs/build/tex_en
            ./SMDExplorer-Documentation/docs/build/tex_ja
          overwrite: true
          retention-days: 1
